spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET:MySecretKeyForJWTGenerationThatIsVerySecure12345}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
springdoc.api-docs.title=Ejercicio Java UserAPI
springdoc.api-docs.description=Microservicio para creación y consulta de usuarios
springdoc.api-docs.version=V3